light-speed/light-speed-rev1

client/components/World.js
=> Fixed earth render bug

client/components/World.js, public/three/FlyControls.js
=> smaller hitbox, hitbox on player obj, invisible hitbox

public/style.css
=> responsive menu background

client/components/World.js
=> hotfix for hitbox

client/components/HUD.js, client/components/World.js, client/store/game.js, client/store/index.js
=> Live score

client/components/HowToPlay.js, client/components/Menu.js, client/components/MenuButton.js, client/routes.js, public/style.css
=> added how to play component format

client/components/World.js, public/three/FlyControls.js
=> Movement changes

client/components/World.js
=> ADD ring direction material

client/components/World.js, public/three/FlyControls.js
=> temp commit

client/components/HUD.js, client/components/Timer.js
=> adds timer countdown

client/components/HUD.js, public/style.css
=> adds jet trails

client/components/auth-form.js, public/style.css
=> caps all menu buttons

client/3d/asteroids.js, client/3d/index.js, client/3d/ring.js, client/components/Timer.js, client/socket.js, client/store/game.js, server/game/Game.js, server/game/index.js, server/socket/index.js
=> Tune gameplay

client/3d/asteroids.js, client/3d/index.js, client/3d/ring.js, package-lock.json, package.json
=> Asteroids overhaul (lag fix)

client/3d/asteroids.js, client/3d/index.js
=> in master, committing to make a new branch

package-lock.json, package.json
=> Fix deploy

client/3d/index.js, client/3d/player.js
=> fixed local vs prod child array bug

server/game/Game.js
=> Nerf dakota

client/components/Credits.js, public/style.css
=> centered credits

README.md
Also removed an extra parens at the bottom of the readme
=> Add link to deployed site in readme

package-lock.json, package.json, server/index.js
=> fix vulnerabilities
